### PR TITLE
Fixes "Long strings of text break profile width"

### LINKED ISSUE #43: `Profiles` Long strings of text break profile width
Can be bit of a pain considering there is no easy way to move sideways on the profiles
Even worse is the user banner svg becoming absolutely massive with a long enough comment

With current location, interests & occupation
image

With goals
image

With comments
image

### PR DESCRIPTION
**Pull request by Yukinyaaa**
fixes #43 
I edited the css of general (global), which may have interfered with other pages.

Best code for testing styles:
```html
<style>
.osekai__2col_col1, .osekai__2col_col2 {
    flex: 1;
    max-width: 100%;
    min-width: 0;
}

.profiles__cover-back-info_text {
    max-width: 100%;
}

.profiles__cover-back-info_text p:not(#arrival__date):not(#hardware) {
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow-x: hidden;
}

.comments__comment-top-text {
    word-break: break-word;
}
</style>
```

### CODE REVIEW

**Comment by yuzupon1133** [comment]
image
max-width: 1200px
image
max-width: 600px
image

**Comment by Tanza3D** [comment]
hm, it works, but i feel there must be a better way to go about it. i'll look into it and if i can't find anything i'll merge

**Comment by Tanza3D** [comment]
@yuzupon1133 applying this code removes the need for the extremely specific max-width requirements, please replace with it. the text modification with ellipsis is good

```css
.osekai__2col_col1, .osekai__2col_col2 {
  flex: 1;
  max-width: 100%;
  min-width: 0;
}
```
(you will need to edit global/css/main.css)

**Comment by yuzupon1133** [comment]
> @ yuzupon1133 applying this code removes the need for the extremely specific max-width requirements, please replace with it. the text modification with ellipsis is good
> 
> ```css
> .osekai__2col_col1, .osekai__2col_col2 {
>   flex: 1;
>   max-width: 100%;
>   min-width: 0;
> }
> ```
> 
> (you will need to edit global/css/main.css)

Thanks for the ideas.

**Pull request closed without merging**
