### PR TITLE
sexy new theme

### PR DESCRIPTION
**Pull request by Tanza3D**

### CODE REVIEW

**Comment by ly-nld** [comment]
what

**Comment by Tanza3D** [comment]
idea is to mirror octon to get people kinda used to the new colours before rolling out the new ui as well

**Review by TheEggo — APPROVED** [review]

**Comment by ly-nld** [comment]
> idea is to mirror octon to get people kinda used to the new colours before rolling out the new ui as well

so you are leaking the new secret not secret project

**Review by minusQuantumNeko — APPROVED** [review]
Sure, lol

**Comment by Tanza3D** [comment]
> > idea is to mirror octon to get people kinda used to the new colours before rolling out the new ui as well
> 
> so you are leaking the new secret not secret project

people know of octon it's just that people don't know what octon contains :)

**Review by loma-baldsson — COMMENTED** [review]
yep that's my email

**Pull request merged**
