### PR TITLE
Prevent overflow of donation percentage bar.

### PR DESCRIPTION
**Pull request by Coppertine**
Not tested because I don't want to ruin my admin branch for now.

### CODE REVIEW

**Comment by Tanza3D** [comment]
not sure if this'd work? will have to test in a bit

**Comment by Coppertine** [comment]
I hate having to wanting to change main branches, but not wanting to discard any changes from admin branch.. AAAA so a github edit was made..

**Comment by Coppertine** [comment]
oh.. i forgot,

**Comment by Tanza3D** [comment]
feel free to change the admin submodule in prs, the prod server ignores the submodules anyway and force merges the admin folder to main so

**Review by Tanza3D — APPROVED** [review]
seems good

**Pull request merged**
